// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okhbqwkuavrexevhuvcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raGJxd2t1YXZyZXhldmh1dmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTY2OTEsImV4cCI6MjA2MzE3MjY5MX0.CDsLwhsaYgLBsNyh0JAZRvHi5wx2LLBuNWFl2FE-ayU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);