// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skwomsadjuxughbogcuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrd29tc2FkanV4dWdoYm9nY3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODQ3MTAsImV4cCI6MjA2MjI2MDcxMH0.nPPwpliwt_vFxrylLUkCguvcFuuZD6l4mdSDJ39QEko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);